/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.absenrfid.view;

/**
 *
 * @author user
 */
public class HapusVisitor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HapusVisitor.class.getName());

    /**
     * Creates new form HapusVisitor
     */
    public HapusVisitor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWadah = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblIngat = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlWadah.setBackground(new java.awt.Color(102, 0, 0));

        lblJudul.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Hapus Visitor");

        lblIngat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIngat.setForeground(new java.awt.Color(255, 255, 255));
        lblIngat.setText("Anda yakin ingin menghapus?");

        btnBatal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBatal.setText("Batal");

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");

        javax.swing.GroupLayout pnlWadahLayout = new javax.swing.GroupLayout(pnlWadah);
        pnlWadah.setLayout(pnlWadahLayout);
        pnlWadahLayout.setHorizontalGroup(
            pnlWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWadahLayout.createSequentialGroup()
                .addGroup(pnlWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWadahLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblJudul))
                    .addGroup(pnlWadahLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlWadahLayout.createSequentialGroup()
                                .addComponent(btnHapus)
                                .addGap(60, 60, 60)
                                .addComponent(btnBatal))
                            .addComponent(lblIngat))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlWadahLayout.setVerticalGroup(
            pnlWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWadahLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblJudul)
                .addGap(26, 26, 26)
                .addComponent(lblIngat)
                .addGap(42, 42, 42)
                .addGroup(pnlWadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnHapus))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWadah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWadah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                HapusVisitor dialog = new HapusVisitor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel lblIngat;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel pnlWadah;
    // End of variables declaration//GEN-END:variables
}
