/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.absenrfid.view;
import com.mycompany.absenrfid.services.AuthService;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import com.mycompany.absenrfid.services.I18nService;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame 
    implements I18nService.I18nChangeListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
        public Login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        I18nService.registerListener(this);
        onLanguageChanged();
    }

            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
        @Override
    public void onLanguageChanged() {
        lblTitle.setText(I18nService.get("ui.title.login"));
        lblUserTitle.setText(I18nService.get("ui.label.username"));
        lblPassTitle.setText(I18nService.get("ui.label.password"));
        btnLogin.setText(I18nService.get("ui.btn.login"));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUserTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Nexa.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 500, 260));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblTitle.setText("Login NEXA");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        lblUserTitle.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        lblUserTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblUserTitle.setText("USERNAME");
        getContentPane().add(lblUserTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txtUsername.setBackground(new java.awt.Color(204, 204, 204));
        txtUsername.setToolTipText("Masukan username anda");
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 300, 40));

        lblPassTitle.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        lblPassTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblPassTitle.setText("PASSWORD");
        getContentPane().add(lblPassTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        btnLogin.setBackground(new java.awt.Color(153, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 80, 30));

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        doLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    
    private void doLogin() {
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                I18nService.get("ui.msg.usernamekosong"));
            txtUsername.requestFocus();
        } else if (password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                I18nService.get("ui.msg.passwordkosong"));
            txtPassword.requestFocus();
        } else {
            I18nService.unregisterListener(this);
            new com.mycompany.absenrfid.services.AuthService().login(username, password, this);
        }
    }
    
}
