/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.absenrfid.view;

import com.mycompany.absenrfid.objects.Visitor;
import com.mycompany.absenrfid.serial.SerialDataHandler;
import com.mycompany.absenrfid.services.SerialService;
import com.mycompany.absenrfid.services.VisitorService;
import com.mycompany.absenrfid.services.LogAbsensiService;
import com.mycompany.absenrfid.util.SecurityUtils;
import javax.swing.SwingUtilities;
import com.mycompany.absenrfid.services.I18nService;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author user
 */
public class MenuAbsen extends javax.swing.JFrame 
    implements I18nService.I18nChangeListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAbsen.class.getName());
    
    private SerialDataHandler<String> rfidHandler;
    Thread delayThread;
    private final VisitorService visitorService = new VisitorService();
    private final LogAbsensiService logService = new LogAbsensiService();

    /**
     * Creates new form MenuAbsen
     */
    public MenuAbsen() {
    initComponents();
    setLocationRelativeTo(null);
    loadLogo();
    pnlResult.setVisible(false);
    I18nService.registerListener(this);
    onLanguageChanged(); // terapkan bahasa saat ini
    registerHandler();
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            I18nService.unregisterListener(MenuAbsen.this);
            if (rfidHandler != null) {
                SerialService.getInstance().removeHandler(rfidHandler);
            }
        }
    });
}
    
    @Override
    public void onLanguageChanged() {
        lblStatus.setText(I18nService.get("ui.welcome"));
    }
    
    private void loadLogo() {
    try {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource("/Logo Nexa.png"));
        java.awt.Image scaled = icon.getImage()
            .getScaledInstance(300, 120, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new javax.swing.ImageIcon(scaled));
        lblLogo.setText("");
    } catch (Exception e) {
        System.out.println("Gagal memuat logo: " + e.getMessage());
    }
}
    

    private void updateLabelWithDelay() {
        if (delayThread != null && delayThread.isAlive()) {
            delayThread.interrupt();
        }
        delayThread = new Thread(() -> {
            try {
                for (int i = 3; i >= 1; i--) {
                    Thread.sleep(1000);
                }
                SwingUtilities.invokeLater(() -> {
                    pnlResult.setVisible(false);
                    lblStatus.setVisible(true);
                });
            } catch (InterruptedException e) {
                // thread dihentikan paksa saat kartu baru di-tap sebelum 3 detik
            }
        });
        delayThread.setName("delayThread");
        delayThread.setDaemon(true);
        delayThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblKeterangan = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        btnSimulasi = new javax.swing.JButton();
        lblTanggalJam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 600));

        lblLogo.setPreferredSize(new java.awt.Dimension(400, 150));

        lblStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(102, 0, 0));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Silahkan Scan Kartu Anda");
        lblStatus.setPreferredSize(new java.awt.Dimension(500, 40));

        pnlResult.setBackground(new java.awt.Color(0, 153, 0));
        pnlResult.setPreferredSize(new java.awt.Dimension(500, 80));
        pnlResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNama.setBackground(new java.awt.Color(255, 255, 255));
        lblNama.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("Nama");
        lblNama.setPreferredSize(new java.awt.Dimension(500, 35));
        pnlResult.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 500, 35));

        lblKeterangan.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Success");
        pnlResult.add(lblKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 500, 25));

        txtUID.setText("Masukkan UID Kartu");
        txtUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUIDActionPerformed(evt);
            }
        });

        btnSimulasi.setBackground(new java.awt.Color(102, 0, 0));
        btnSimulasi.setForeground(new java.awt.Color(255, 255, 255));
        btnSimulasi.setText("Absen");
        btnSimulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulasiActionPerformed(evt);
            }
        });

        lblTanggalJam.setBackground(new java.awt.Color(102, 0, 0));
        lblTanggalJam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTanggalJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggalJam.setText("Waktu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimulasi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(lblTanggalJam, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTanggalJam)
                .addGap(83, 83, 83)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimulasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUIDActionPerformed

    private void btnSimulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulasiActionPerformed
        String uid = txtUID.getText().trim();
        if (uid.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan UID terlebih dahulu!");
            return;
        }
        // Simulasi tap kartu — broadcast ke SerialService
        SerialService.getInstance().simulateBroadcast(uid);
        txtUID.setText("");
   
    }//GEN-LAST:event_btnSimulasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAbsen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimulasi;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggalJam;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables

    private void registerHandler() {
        startClock();
    rfidHandler = dataRfid -> {
        String hashedUid = SecurityUtils.getHash(dataRfid, SecurityUtils.SHA_256);
        Visitor visitor = visitorService.cariByUidHash(hashedUid);

        SwingUtilities.invokeLater(() -> {
            if (visitor != null) {
                logService.simpanLog(hashedUid, visitor.getNama(), visitor.getNim(), visitor.getKelas(), "Berhasil");
                lblNama.setText(visitor.getNama());
                lblKeterangan.setText(I18nService.get("ui.status.success"));
                pnlResult.setBackground(new java.awt.Color(0, 153, 0));
                pnlResult.setVisible(true);
                lblStatus.setVisible(false);
            } else {
                logService.simpanLog(hashedUid, "Unknown", "-", "-", "Gagal");
                lblNama.setText(I18nService.get("ui.status.failed"));
                lblKeterangan.setText("Scan Ulang / Daftar Dulu");
                pnlResult.setBackground(new java.awt.Color(204, 0, 0));
                pnlResult.setVisible(true);
                lblStatus.setVisible(false);
            }
            updateLabelWithDelay();
        });
    };
    SerialService.getInstance().addHandler(rfidHandler);
}
    
    private void startClock() {
    Thread t = new Thread(() -> {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy  HH:mm:ss", new java.util.Locale("id", "ID"));
        while (!Thread.currentThread().isInterrupted()) {
            String waktu = LocalDateTime.now().format(formatter);
            SwingUtilities.invokeLater(() -> lblTanggalJam.setText(waktu));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
    });
    t.setName("Clock-MenuAbsen");
    t.setDaemon(true);
    t.start();
}
}
