/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.absenrfid.view;

import com.mycompany.absenrfid.objects.Visitor;
import com.mycompany.absenrfid.serial.SerialDataHandler;
import com.mycompany.absenrfid.services.SerialService;
import com.mycompany.absenrfid.services.VisitorService;
import com.mycompany.absenrfid.services.LogAbsensiService;
import com.mycompany.absenrfid.util.EncryptionUtils;
import java.awt.Color;
import javax.swing.SwingUtilities;
/**
 *
 * @author user
 */
public class MenuAbsen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAbsen.class.getName());
    
    private SerialDataHandler<String> rfidHandler;
    private final VisitorService visitorService = new VisitorService();
    private final LogAbsensiService logService = new LogAbsensiService();

    /**
     * Creates new form MenuAbsen
     */
    public MenuAbsen() {
        initComponents();
        setLocationRelativeTo(null);
        loadLogo();
        pnlResult.setVisible(false);
        startRfidListener();
        
        // Bersihkan handler saat form ditutup
        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (rfidHandler != null) {
                SerialService.getInstance().removeHandler(rfidHandler);
            }
        }
    });
    }
    
    private void loadLogo() {
    try {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource("/Logo Nexa.png"));
        java.awt.Image scaled = icon.getImage()
            .getScaledInstance(300, 120, java.awt.Image.SCALE_SMOOTH);
        lblLogo.setIcon(new javax.swing.ImageIcon(scaled));
        lblLogo.setText("");
    } catch (Exception e) {
        System.out.println("Gagal memuat logo: " + e.getMessage());
    }
}
    
    private void startRfidListener() {
    rfidHandler = (String rawUid) -> {
        SwingUtilities.invokeLater(() -> prosesUid(rawUid));
    };
    SerialService.getInstance().addHandler(rfidHandler);
}
    
    private void prosesUid(String rawUid) {
    String encryptedUid = EncryptionUtils.encrypt(rawUid);
    Visitor visitor = visitorService.cariByUidEncrypted(encryptedUid);

    if (visitor != null) {
        tampilHasil(visitor.getNama(), "Success", new Color(0, 153, 0));
        simpanLog(visitor, rawUid, "Berhasil");
    } else {
        tampilHasil("Kartu Tidak Terdaftar", "Scan Ulang / Daftar Dulu", new Color(204, 0, 0));
        simpanLogGagal(rawUid);
    }

    new Thread(() -> {
        try {
            Thread.sleep(3000);
            SwingUtilities.invokeLater(this::kembaliIdle);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }).start();
}
    
    private void tampilHasil(String nama, String keterangan, Color warna) {
    lblNama.setText(nama);
    lblKeterangan.setText(keterangan);
    pnlResult.setBackground(warna);
    pnlResult.setVisible(true);
    lblStatus.setVisible(false);
    }

    private void kembaliIdle() {
        pnlResult.setVisible(false);
        lblStatus.setVisible(true);
    }

    private void simpanLog(Visitor v, String rawUid, String status) {
    logService.simpanLog(
        EncryptionUtils.encrypt(rawUid),
        v.getNama(),
        v.getNim(),
        v.getKelas(),
        status
        );
    }

    private void simpanLogGagal(String rawUid) {
    logService.simpanLog(
        EncryptionUtils.encrypt(rawUid),
        "Unknown", "-", "-",
        "Gagal - UID tidak terdaftar"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblKeterangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        lblLogo.setPreferredSize(new java.awt.Dimension(400, 150));

        lblStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(102, 0, 0));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Silahkan Scan Kartu Anda");
        lblStatus.setPreferredSize(new java.awt.Dimension(500, 40));

        pnlResult.setBackground(new java.awt.Color(0, 153, 0));
        pnlResult.setPreferredSize(new java.awt.Dimension(500, 80));
        pnlResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNama.setBackground(new java.awt.Color(255, 255, 255));
        lblNama.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("Nama");
        lblNama.setPreferredSize(new java.awt.Dimension(500, 35));
        pnlResult.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 500, 35));

        lblKeterangan.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        lblKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeterangan.setText("Success");
        pnlResult.add(lblKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 500, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAbsen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlResult;
    // End of variables declaration//GEN-END:variables
}
