/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.absenrfid.view;

/**
 *
 * @author user
 */
public class Monitoring extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Monitoring.class.getName());

    /**
     * Creates new form Monitoring
     */
    public Monitoring() {
        initComponents();
        
        setupNavigation();
        
        loadData();
}
    
    private void setupNavigation() {
        
    btnNavVisitor.addActionListener(e ->{
        new DataVisitor().setVisible(true);
        this.dispose();
    });
    
    btnNavAbsensi.addActionListener(e ->{
       new Absensi().setVisible(true);
       this.dispose();
    });
    
    btnNavPengaturan.addActionListener(e ->{
        new Pengaturan().setVisible(true);
        this.dispose();
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnNavPengaturan = new javax.swing.JButton();
        btnNavMonitoring = new javax.swing.JButton();
        btnNavVisitor = new javax.swing.JButton();
        btnNavAbsensi = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        lblAdminProfile = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        pnlVisitorCard = new javax.swing.JPanel();
        lblVisitorCount = new javax.swing.JLabel();
        cbFilterProdi = new javax.swing.JComboBox<>();
        cbFilterKelas = new javax.swing.JComboBox<>();
        btnSimpanFilter = new javax.swing.JButton();
        lblVisitorLabel = new javax.swing.JLabel();
        scrollTblMonitoring = new javax.swing.JScrollPane();
        tblMonitoring = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidebar.setBackground(new java.awt.Color(102, 0, 0));
        pnlSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Profil.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(180, 90));
        pnlSidebar.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 100));

        btnNavPengaturan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNavPengaturan.setText("Pengaturan");
        pnlSidebar.add(btnNavPengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 30));

        btnNavMonitoring.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNavMonitoring.setText("Monitoring");
        btnNavMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavMonitoringActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnNavMonitoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 30));

        btnNavVisitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNavVisitor.setText("Data Visitor");
        btnNavVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavVisitorActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnNavVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 30));

        btnNavAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNavAbsensi.setText("Absensi");
        pnlSidebar.add(btnNavAbsensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 30));

        getContentPane().add(pnlSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        pnlHeader.setBackground(new java.awt.Color(153, 0, 0));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("MONITORING");
        pnlHeader.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblSubtitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setText("Pantau kehadiran siswa secara realtime");
        pnlHeader.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblAdminName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAdminName.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminName.setText("Admin");
        pnlHeader.add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 40, -1, 20));

        lblAdminProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profil.png"))); // NOI18N
        pnlHeader.add(lblAdminProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 40, 40));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, 100));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClock.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblClock.setText("23 Jan 2026 10:08");
        pnlContent.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 60));

        lblVisitorCount.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblVisitorCount.setText("4");
        pnlVisitorCard.add(lblVisitorCount);

        pnlContent.add(pnlVisitorCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 60));

        cbFilterProdi.setBackground(new java.awt.Color(204, 204, 204));
        cbFilterProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilterProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterProdiActionPerformed(evt);
            }
        });
        pnlContent.add(cbFilterProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 80, -1));

        cbFilterKelas.setBackground(new java.awt.Color(204, 204, 204));
        cbFilterKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilterKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterKelasActionPerformed(evt);
            }
        });
        pnlContent.add(cbFilterKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 90, 80, -1));

        btnSimpanFilter.setBackground(new java.awt.Color(51, 204, 0));
        btnSimpanFilter.setText("Simpan");
        pnlContent.add(btnSimpanFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        lblVisitorLabel.setText("Visitor Hari Ini");
        pnlContent.add(lblVisitorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        scrollTblMonitoring.setBackground(new java.awt.Color(153, 153, 153));

        tblMonitoring.setBackground(new java.awt.Color(204, 204, 204));
        tblMonitoring.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Waktu", "NIM", "Nama", "Kelas"
            }
        ));
        tblMonitoring.setRowHeight(30);
        tblMonitoring.setShowHorizontalLines(true);
        scrollTblMonitoring.setViewportView(tblMonitoring);

        pnlContent.add(scrollTblMonitoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1020, 400));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 1060, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavVisitorActionPerformed
new DataVisitor().setVisible(true); 
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnNavVisitorActionPerformed

    private void cbFilterKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilterKelasActionPerformed

    private void btnNavMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMonitoringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavMonitoringActionPerformed

    private void cbFilterProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilterProdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Monitoring().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNavAbsensi;
    private javax.swing.JButton btnNavMonitoring;
    private javax.swing.JButton btnNavPengaturan;
    private javax.swing.JButton btnNavVisitor;
    private javax.swing.JButton btnSimpanFilter;
    private javax.swing.JComboBox<String> cbFilterKelas;
    private javax.swing.JComboBox<String> cbFilterProdi;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblAdminProfile;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVisitorCount;
    private javax.swing.JLabel lblVisitorLabel;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlVisitorCard;
    private javax.swing.JScrollPane scrollTblMonitoring;
    private javax.swing.JTable tblMonitoring;
    // End of variables declaration//GEN-END:variables
private void loadData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMonitoring.getModel();
        model.setRowCount(0);
        try {
            com.mongodb.client.MongoDatabase db = com.mycompany.absenrfid.objects.MongoManager.getDatabase();
            com.mongodb.client.MongoCollection<org.bson.Document> col = db.getCollection("LogAbsensi");
            for (org.bson.Document doc : col.find()) {
                Object[] row = {
                    doc.getString("waktu"),
                    doc.getString("nim"),
                    doc.getString("nama"),
                    doc.getString("kelas")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
}
